from classes import Item

AnyWeapon = Item(name='Weapon', hash=1)
FirstSlotWeapons = Item(name='Kinetic Weapon', hash=2)
SecondSlotWeapons = Item(name='Energy Weapon', hash=3)
PowerWeapons = Item(name='Power Weapon', hash=4)
AutoRifles = Item(name='Auto Rifle', hash=5)
HandCannons = Item(name='Hand Cannon', hash=6)
PulseRifles = Item(name='Pulse Rifle', hash=7)
ScoutRifles = Item(name='Scout Rifle', hash=8)
FusionRifles = Item(name='Fusion Rifle', hash=9)
SniperRifles = Item(name='Sniper Rifle', hash=10)
Shotguns = Item(name='Shotgun', hash=11)
MachineGuns = Item(name='Machine Gun', hash=12)
RocketLaunchers = Item(name='Rocket Launcher', hash=13)
Sidearms = Item(name='Sidearm', hash=14)
Swords = Item(name='Sword', hash=54)
GrenadeLaunchers = Item(name='Grenade Launchers', hash=56)
LinearFusionRifles = Item(name='Linear Fusion Rifles', hash=1504945536)
TraceRifles = Item(name='Trace Rifles', hash=2489664120)
Bows = Item(name='Bows', hash=3317538576)
Glaives = Item(name='Glaives', hash=3871742104)
SubmachineGuns = Item(name='Submachine Guns', hash=3954685534)

AnyArmor = Item(name='Armor', hash=20)
Helmets = Item(name='Helmets', hash=45)
Gauntlets = Arms = Item(name='Arms', hash=46)
ChestArmor = Item(name='Chest', hash=47)
LegArmor = Item(name='Legs', hash=48)
ClassItems = Item(name='Class Items', hash=49)

del Item
